### ISSUE TITLE
Set up the jupyter image build pipeline pushing to Quay

### ISSUE THREAD

**Issue by tumido** [aicoe-aiops/categorical-encoding#2]
We need a separate build pipeline for this repository, that would create an s2i custom notebook image out of this repo and publish it to public quay (not internal registry).

@harshad16 @4n4nd  can you please help me with that?

**Comment by 4n4nd** [comment]
@tumido I think this issue will be more suitable for the [build-pipeline repo](https://github.com/thoth-station/jupyternb-build-pipeline/blob/master/tasks/jupyternb-build-release.yaml#L125)

**Comment by tumido** [comment]
Thank you. I'll reference it there. :slightly_smiling_face:

**Comment by tumido** [comment]
Closed via #3
