### ISSUE TITLE
Add  recording to Operate First Blog Post

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/categorical-encoding#24]
The recording of the DS meetup was a good explanation and walk through of this work. We should add it to our youtube channel and include the video in the [blog](https://www.operate-first.cloud/data-science/categorical-encoding/docs/blog/blog.md) .

**Comment by Shreyanand** [comment]
Hey! I also did an overview video when we were reviewing these videos in the team meetings.
[Demo](https://drive.google.com/file/d/1sKaWY5lljbnN5h-Eng0VaU6fON7usK5t/view?usp=sharing) This was the second iteration that I did after everyone's feedback. 
I'm ok with either of those going up, just letting you know of the content that exists :)

**Comment by oindrillac** [comment]
Let's try to put the more polished or _lgtm'ed_ ones on YouTube. So if the above one is the approved version, I can add that to the channel :)

**Comment by MichaelClifford** [comment]
I thought yesterdays was pretty polished, tbh. Plus it was a full 30 minutes. But yes, let me take a quick second at both of these, but i sure one of them is probably ready for YouTube.

**Comment by oindrillac** [comment]
I might be wrong, but i think shorter, more concise videos with CTAs like "spawn this notebook", "read the blog", "contribute or reach out" would serve as better online content. :slightly_smiling_face:

**Comment by MichaelClifford** [comment]
@oindrillac you are right.  The shorter video @Shreyanand linked above is probably better to include on youtube/operate first blog

**Comment by Shreyanand** [comment]
@oindrillac The shorter one it is then :) Lemme know if you need anything from me.

**Comment by oindrillac** [comment]
Here's a link to the uploaded video: https://youtu.be/9zOSg3KANDA This should be ready to link to the blog :slightly_smiling_face: 
@Shreyanand please let me know if I can add a better title or description.
